/* Sass Document */

$(document).ready(function(){
	"use strict";
	$("#menu").hide();
	$("#box").hide();
	$("#switch").hide();
	$("#pic5").click(function(){
		 $("#menu").slideToggle();
	});
	$("#word12").click(function(){
		 $("#menu").slideToggle();
	});
	$("#word13").click(function(){
		 $("#menu").slideToggle();
	});
	$("#word2").click(function(){
		window.location.href="applyforreimbursement.html";
	});
	$("#word3").click(function(){
		window.location.href="travelfund.html";
	});
	$("#pic12").click(function(){
		window.location.href="contract3.html";
	});
	$("#pic13").click(function(){
		window.location.href="addfile.html";
	});
	$("#pic3").click(function(){
		window.location.href="home.html";
	});
	$("#pic4").click(function(){
		window.location.href="home.html";
	});
	$("#add").click(function(){
		$("#box").show();
	});
	$("#box").click(function(){
		$("#box").hide();
	});
	$("#switch").click(function(){
		$("#switch").toggle();
		$("#switch1").toggle();
	});
	$("#switch1").click(function(){
		$("#switch").toggle();
		$("#switch1").toggle();
	});
});